version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  metrics-network:
    driver: bridge

services:

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - metrics-network
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - metrics-network
    restart: always

  dotnetapp:
    container_name: 'dotnet_app'
    build: ./AppMetrics.Prometeus
    ports:
      - "8585:80"
    networks:
      - metrics-network