global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "dotnet"
    static_configs:
      - targets: ["dotnetapp:80"]
    metrics_path: /metrics-text
    scheme: http